// Demo profiles shown when Supabase has no data yet.
// Reflects the Philippine film & TV industry — NeedACrew × BeScene style.

export type SampleProfile = {
  id: string; slug: string; display_name: string; avatar_url: null;
  role: string; specializations: string[]; experience_level: string;
  city: string; availability: string;
  rate_min: number; rate_max: number; rate_unit: string;
  bio: string;
};

export const SAMPLE_PROFILES: SampleProfile[] = [
  {
    id: "demo-1", slug: "miguel-santos-dp",
    display_name: "Miguel Santos",
    avatar_url: null,
    role: "dp",
    specializations: ["Narrative Film", "Commercial / TVC", "Music Video"],
    experience_level: "senior",
    city: "Quezon City",
    availability: "available",
    rate_min: 8000, rate_max: 12000, rate_unit: "day",
    bio: "15 years behind the lens. Shaped the look of two GMA primetime series and multiple MMFF indie entries. ARRI Amira and RED Dragon certified.",
  },
  {
    id: "demo-2", slug: "krissy-dela-cruz-editor",
    display_name: "Krissy Dela Cruz",
    avatar_url: null,
    role: "editor",
    specializations: ["Drama Series", "Documentary", "Music Video"],
    experience_level: "senior",
    city: "Makati",
    availability: "available",
    rate_min: 6000, rate_max: 9000, rate_unit: "day",
    bio: "Post-production specialist. Co-edited Netflix Philippines' debut documentary and cut 4 GMA drama series. Premiere Pro and DaVinci Resolve.",
  },
  {
    id: "demo-3", slug: "jerome-aquino-sound",
    display_name: "Jerome Aquino",
    avatar_url: null,
    role: "sound_mixer",
    specializations: ["Production Sound", "ADR", "Live Event"],
    experience_level: "senior",
    city: "Pasig",
    availability: "busy",
    rate_min: 4500, rate_max: 6500, rate_unit: "day",
    bio: "Production sound mixer with 12 years on Filipino TV and cinema sets. Sennheiser and Lectrosonics kit owner.",
  },
  {
    id: "demo-4", slug: "ana-reyes-director",
    display_name: "Ana Reyes",
    avatar_url: null,
    role: "director",
    specializations: ["Narrative Film", "Music Video", "Documentary"],
    experience_level: "expert",
    city: "Quezon City",
    availability: "available",
    rate_min: 15000, rate_max: 25000, rate_unit: "day",
    bio: "Multi-awarded MMFF director with 3 features and 40+ music videos for major OPM artists. Clean visual storytelling rooted in Filipino lived experience.",
  },
  {
    id: "demo-5", slug: "carlo-mendoza-gaffer",
    display_name: "Carlo Mendoza",
    avatar_url: null,
    role: "gaffer",
    specializations: ["Studio Lighting", "Location Lighting", "LED / DMX"],
    experience_level: "mid",
    city: "Taguig",
    availability: "available",
    rate_min: 3500, rate_max: 5000, rate_unit: "day",
    bio: "Lighting technician based in BGC. Commercial sets and indie productions. Full LED and DMX kit available for hire.",
  },
  {
    id: "demo-6", slug: "denise-villanueva-pd",
    display_name: "Denise Villanueva",
    avatar_url: null,
    role: "prod_designer",
    specializations: ["Film", "TV Series", "Commercial"],
    experience_level: "senior",
    city: "Cebu City",
    availability: "available",
    rate_min: 6000, rate_max: 9000, rate_unit: "day",
    bio: "Production designer from Cebu with 8 years building sets for TV drama and independent film. Can oversee nationwide scouting and build-outs.",
  },
  {
    id: "demo-7", slug: "rovic-castillo-camera",
    display_name: "Rovic Castillo",
    avatar_url: null,
    role: "camera_op",
    specializations: ["ENG/News", "Multi-camera", "Studio"],
    experience_level: "mid",
    city: "Davao City",
    availability: "busy",
    rate_min: 3000, rate_max: 4500, rate_unit: "day",
    bio: "Broadcast camera op with 7 years at a Davao network. Available for independent shoots and live events on weekends.",
  },
  {
    id: "demo-8", slug: "jade-santos-mua",
    display_name: "Jade Santos",
    avatar_url: null,
    role: "mua",
    specializations: ["Film / TV", "Commercial", "Special Effects"],
    experience_level: "expert",
    city: "Quezon City",
    availability: "available",
    rate_min: 4500, rate_max: 7000, rate_unit: "day",
    bio: "Head makeup artist on 3 GMA primetime teleseryes. SFX certified — prosthetics, aging, wounds, and creature design.",
  },
  {
    id: "demo-9", slug: "lance-bautista-colorist",
    display_name: "Lance Bautista",
    avatar_url: null,
    role: "colorist",
    specializations: ["Film", "TV Series", "Music Video", "DIT On-Set"],
    experience_level: "senior",
    city: "Metro Manila",
    availability: "available",
    rate_min: 7000, rate_max: 11000, rate_unit: "day",
    bio: "Primary colorist and DIT with 9 years grading for broadcast and cinema. DaVinci Resolve certified. On-set DIT kit available.",
  },
  {
    id: "demo-10", slug: "maria-fontanilla-scriptsup",
    display_name: "Maria Fontanilla",
    avatar_url: null,
    role: "script_supervisor",
    specializations: ["Film", "TV Series", "Commercial"],
    experience_level: "mid",
    city: "Quezon City",
    availability: "available",
    rate_min: 3000, rate_max: 4000, rate_unit: "day",
    bio: "Continuity and script supervision across indie features and television. Meticulous on set, skilled with Movie Magic Scheduling.",
  },
  {
    id: "demo-11", slug: "bryan-gonzales-pm",
    display_name: "Bryan Gonzales",
    avatar_url: null,
    role: "prod_manager",
    specializations: ["Film", "TV Series", "Commercial", "Live Event"],
    experience_level: "senior",
    city: "Pasig",
    availability: "busy",
    rate_min: 5500, rate_max: 8000, rate_unit: "day",
    bio: "10+ years managing production logistics across commercial, broadcast, and cinema. Nationwide network of suppliers and locations.",
  },
  {
    id: "demo-12", slug: "pia-torres-vfx",
    display_name: "Pia Torres",
    avatar_url: null,
    role: "vfx",
    specializations: ["Motion Graphics", "Compositing", "Title Design"],
    experience_level: "mid",
    city: "Makati",
    availability: "not_looking",
    rate_min: 5000, rate_max: 8000, rate_unit: "day",
    bio: "Motion graphics designer and compositor. After Effects and Nuke. TV series lower thirds, title sequences, and commercial VFX.",
  },
];
